### ISSUE TITLE
No JS module 'quickSettings' found error

### ISSUE THREAD

**Issue by savvagen** [arononak/github-actions-gnome-extension#4]
Error is raced when running the extension:

```
No JS module 'quickSettings' found in search path
```
What could be the workaround here?

**Comment by arononak** [comment]
@savvagen Hi, thanks for your help,

Could you send me your gnome version and full stacktrace ?

**Comment by arononak** [comment]
@savvagen Still getting bug ? 😄

**Comment by arononak** [comment]
the extension has been migrated to ESM, so I'm closing it
