### ISSUE TITLE
Gnome 46 support

### ISSUE THREAD

**Issue by bhundven** [arononak/github-actions-gnome-extension#6]
Could we add support for Gnome 46?

**Comment by arononak** [comment]
If you give a star, I will increase the supported version, but I will not test whether everything works properly.  You have to wait for Ubuntu 24/04 😄

**Comment by JordanViknar** [comment]
> If you give a star, I will increase the supported version, but I will not test whether everything works properly. You have to wait for Ubuntu 24/04 😄

Bad idea. :-1: 
Don't add support for a shell version in a public release if you cannot confirm your extension will work properly with it, especially just for one star.

![image](https://github.com/arononak/github-actions-gnome-extension/assets/74505993/52da3a1e-4b69-4829-84b3-ad89a1065735)

Anyways, though publishing updates without testing them properly on the GNOME Shell Extensions website was... not the greatest idea, I wonder how you even got approval in fact, I'll explain why this occurs.

From the [guide for upgrading to GNOME Shell 46](https://gjs.guide/extensions/upgrading/gnome-shell-46.html), here's some information :

![image](https://github.com/arononak/github-actions-gnome-extension/assets/74505993/ffd223ee-2358-4a16-a3aa-ef824e844333)

This seemingly also applies to `box.add`, so here's [what I (lazily) did in my own extension](https://github.com/JordanViknar/Noiseclapper-GNOME/commit/2c8f7c3edd5ab84cc091d4fa4b5babce031082ac).

```javascript
try {
	Submenu.menu.box.add_child(this.Button); // GNOME 46+	
} catch {
	Submenu.menu.box.add(this.Button); // GNOME 45
}
```
*(`add_child`/`remove_child` might also work on GNOME 45, I'm not certain...)*

If you'd prefer using other methods, there's [this guide for targeting older GNOME Versions](https://gjs.guide/extensions/development/targeting-older-gnome.html)

**Comment by arononak** [comment]
@JordanViknar 

Not necessarily a bad idea, as it may or may not have worked. Without the correction it would definitely not work. But I still appreciate your contribution and I'll take it into account next month.

If you have any ideas for development, I'd love to read them 😀

**Comment by bhundven** [comment]
I'm on Fedora 40 Workstation prerelease. I'd be happy to test.

**Comment by arononak** [comment]
@bhundven Version 3.22.0 has a number added for Gnome 46, but @JordanViknar wrote that it doesn't work. You have to wait a few more weeks 🙁️

**Comment by arononak** [comment]
@bhundven @JordanViknar I uploaded version 3.27.1 with support for Gnome 46. There are a few minor things to improve, but at least core features works.
