### ISSUE TITLE
After logging in to the Github account on the web, it shows' No permissions'

### ISSUE THREAD

**Issue by Liu020321** [arononak/github-actions-gnome-extension#7]
After logging in to the Github account on the web, it displays' No permissions'. I logged in using the web browser and clicked on the account details to show that all permissions were granted, but star, repository, information, and so on are not displayed. Other functions are normal. May I ask what the reason is? Is there something that hasn't been installed or configured? I changed to token login and gave all permissions, but it still doesn't display. The version is 3.43.0; The GitHub CLI version is 2.45.0.
![image](https://github.com/user-attachments/assets/65d0bb30-6c32-4697-8685-be01cac33a4d)

**Comment by Liu020321** [comment]
![image](https://github.com/user-attachments/assets/4b3111e8-779c-49fc-80ac-9998d98ecc01)

**Comment by arononak** [comment]
@Liu020321 Hi, thanks for reporting. Could you tell me what scopes you have in GitHub CLI?

https://github.com/arononak/github-actions-gnome-extension?tab=readme-ov-file#-installation

**Comment by Liu020321** [comment]
![image](https://github.com/user-attachments/assets/3b839a9c-2e8b-40bf-bb87-bd6f6bc7999b)
Is this one?

**Comment by arononak** [comment]
@Liu020321 I checked your account and you don't have an email set. I thought this field would never be null/undefined. I fixed it and released a new version. Gnome should release it today or tomorrow. So you need to update the extension version or set an email in the current version. Let me know if it helps.

`gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /users/Liu020321`

https://github.com/arononak/github-actions-gnome-extension/commit/d7a6b68239447e47ff935f8ad08435af92534e5b
https://github.com/arononak/github-actions-gnome-extension/commit/de041bf92e16dcf587ab4c7a1b5097d90619eefb

I'm also curious why your texts are cut off in half?

**Comment by Liu020321** [comment]
I just checked my Github account and I bound my email. It shouldn't show as null. When I first started learning to use Github, I registered my email. How can I identify this email? Additionally, only half of my fonts were displayed, which is likely due to my beautification theme. Even after uninstalling the theme, some of my fonts were still obscured, but they returned to normal after restarting. Do you have any way to solve this. Thank you.
![image](https://github.com/user-attachments/assets/2dc74e72-9939-4220-976b-60c8b9771337)

**Comment by arononak** [comment]
I think you need to set a publicly visible email address. Not the one in your account settings.

![Screenshot](https://github.com/user-attachments/assets/6af556d7-91b8-41a5-92e5-b59d7f8ced53)

I have no idea how to fix it quickly 😕️ If you care, you can try to fix it. The description of how to develop the extension is in README.md 😁️

**Comment by Liu020321** [comment]
Thank you very much. I have resolved the issue and apologize for any inconvenience caused due to my settings. Thank you again, your plugin is very useful!

**Comment by arononak** [comment]
that's what I'm here for, to help 😄
